<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\Icons\Bezier.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Dirkster.AvalonDock" />
    <PackageReference Include="Dirkster.AvalonDock.Themes.VS2013" />
    <PackageReference Include="FluentIcons.Wpf" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="SharpVectors.Wpf" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.Views.WPF" />
    <PackageReference Include="Svg.Skia" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\VsCodeDarkXml.xshd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\icons.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="Resources\Icons\Bezier.ico" />
    <Resource Include="Resources\Icons\Bezier_32.png" />
    <Resource Include="Resources\Icons\Bezier.svg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bezier.Core\Bezier.Core.csproj" />
  </ItemGroup>

</Project>
