<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <RootNamespace>Imago.FileFormats</RootNamespace>
    <AssemblyName>Imago.FileFormats</AssemblyName>
    <Description>Image file format support for Imago</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Imago.Core\Imago.Core.csproj" />
  </ItemGroup>

</Project>
