<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <RootNamespace>Pinxit.FileFormats</RootNamespace>
    <AssemblyName>Pinxit.FileFormats</AssemblyName>
    <Description>Image file format support for Pinxit</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pinxit.Core\Pinxit.Core.csproj" />
  </ItemGroup>

</Project>
